version: "3.7"

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # Can set another path 
      - mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST:-mysql}
      PMA_PORT: ${MYSQL_PORT:-3306}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-100M}
    # depends_on:
    #   - mysql

  # web-server
  proxy:
    environment:
      - ACME_AGREE=true
    build:
      context: ./caddy
  
  # mail-server
  mail:
    image: mailhog/mailhog

  rtcmultyconnection:
    tty: true
    build:
      context: ./rtcmultyconnection
    command: yarn --ignore-engines start

  coturn:
    build:
      context: ./coturn
    volumes:
      - ./coturn/turnserver.conf:/etc/turnserver.conf
    ports:
      ## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      # - "80:80"
      # - "80:80/udp"
      ## STUN/TURN SSL
      # - "5349:5349"
      # - "5349:5349/udp"
      # - "5350:5350"
      # - "5350:5350/udp"
      # - "443:443"
      # - "443:443/udp"
      # Relay Ports
      #      - "49152-65535:49152-65535"
      #      - "49152-65535:49152-65535/udp"
      

volumes:
  mysql:

networks:
  default:
    name: ${NETWORK_NAME:-prisma-cms-default}
