version: "3.7"

services:

  mysql:
    ports:
      - '3306:3306'

  proxy:
    ports:
      - 2015:2015
      - 2016:2016
      - 2017:2017

  pma:
    ports:
      - 8090:80

  mail:
    ports:
      - 8025:8025
