version: "3.7"

services:

  mysql:
    restart: always

  pma:
    restart: always

  proxy:
    restart: always
    environment:
      - ACME_AGREE=true
    ports:
      - 80:80
      - 443:443

  rtcmultyconnection:
    restart: always

  coturn:
    restart: always
